# fileStream = open("FileHandling.txt", 'r+')
# fileStream.write("dgijbmk")
# data = fileStream.read()
# print(data)
# data = fileStream.readline()
# print(data)
# data = fileStream.readline()
# print(data)
# data = fileStream.readline()
# print(data)
# data = fileStream.readline()
# print(data)
# data = fileStream.readline()
# print(data)
# data = fileStream.read(100)
# print(data)
# fileStream.close()

# fileStream = open("FileHandling2.txt", 'a')
# fileStream.write("bye python")
# fileStream.close()

# fileStream = open("FileHandling2.txt", 'w+')
# fileStream.write("abcd")
# fileStream.seek(0)
# print(fileStream.read())

# fileStream = open("FileHandling.txt", 'a+')
# fileStream.write("\nline pinted by a+ mode")
# fileStream.seek(0)
# print(fileStream.read())

fileStream = open("mobile.jpeg", 'rb')
data = fileStream.read(2000)
# print(data)
# # print(type(data))

fileStream = open("mobile-copy.jpeg", 'wb')
fileStream.write(data)
